org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# ESTA LÍNEA ES VITAL: Obliga a las librerías viejas (como Isar) a adaptarse a AndroidX
android.enableJetifier=true
# Evita que se usen SDKs experimentales que causan el error de lStar
android.suppressUnsupportedCompileSdk=34